[package]
name = "sec10-wordcount"
version = "0.1.0"
authors = ["modeverv <modeverv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
license = "MIT OR Apache-2.0"

[dependencies]
regex = "1.0"
